version: 2
sphinx:
    configuration: doc/conf.py


formats: all

python:
    version: 3.6
    install:
        - requirements: requirements.txt
        - requirements: requirements_dev.txt
        - requirements: requirements_rtd.txt
        - method: pip
          path: .
