name: sequana

channels:
- bioconda
- defaults
- r
- conda-forge

dependencies:
- python=3.5
- numpy
- pandas
- matplotlib
- pysam
#- reports
- easydev>=0.9.36
- bioservices
- pip
- shustring
- biokit>=0.4.3
- ruamel.yaml
- kraken
- krona
#- pygraphviz
- snakemake==4.5.0
- urllib3==1.22 # to fix bug in RTD (oct2017)

- pip:
  - ipython
  - jupyter
  - docutils<0.13.1 # https://github.com/sphinx-doc/sphinx/issues/3212

