name: sequana

channels:
- conda-forge
- bioconda
- defaults

dependencies:
- python=3.6
- numpy
- pandas
- matplotlib
- pysam
- easydev>=0.9.36
- bioservices
- pip
- shustring
- ruamel.yaml
- kraken
- krona
- shustring
- sklearn

- pip:
  - ipython
  - jupyter
  - docutils<0.13.1 # https://github.com/sphinx-doc/sphinx/issues/3212

