# ============================================================================
# Config file for RNA-seq
#
# ==================[ Sections for the users ]================================
#
# One of input_directory, input_pattern and input_samples must be provided
# If input_directory provided, use it otherwise if input_pattern provided,
# use it, otherwise use input_samples.
# If input_extension provided, use it otherwise assume fastq.gz
# ============================================================================
input_directory: "%(input_directory)s"
input_readtag: "%(input_readtag)s"
input_pattern: "%(input_pattern)s"
input_extension: "%(input_extension)s"
# =========================================== Sections for the users

# list of your input file
input_samples:
    file1: "%(file1)s"
    file2: "%(file2)s"

# if files are required for a pipeline and are within sequana or should
# be downloaded before the pipeline provide them in this section
# Note that sequana and url fields are followed by itemised files or links
# using the front dashes
requirements:
    - Institut_Pasteur.png



##################################################################
# sequencing information. These informations will be inserted as
# read group in BAM files
#
# :Parameters:
#
# - platform: Name of the sequencing platform
# - instrument: name ot the instrument type
# - flowcell: flowcell ID

sequencing:
    platform: "Illumina"
    instrument: "Hiseq2500"
    flowcell: "H35CTBCXY"

##################################################################
# Design information. These informations will be used during the
# peak calling step
#
# :Parameters:
#
# - design_file: Path to a design file in tabulated format. See documentation
# - spike: set to 'yes' if you have spikes in your data. Possible values: {yes, no}
# - marks: list of different marks of transcription factors (comma-separated)
# - condition: list of different conditions (comma-separated). NB: cond1 must be the reference condition
# - replicates: How the replicate is writed in the files (REP or Rep or rep ?)

design:
    design_file: /path/to/your/design_file.txt
    marks: Mark1, Mark2
    condition: Cond1, Cond2
    replicates: Rep
    spike: no
    spike_genome_file: /path/to/your/directory/Genomes/spike_genome/spike_genome.fa



#############################################################################
# Indexing section: if checked, all index for bowtie (1&2), star, etc... will be produced in dir
#
# :Parameters:
#
# - index: if checked, this rule will process all index files. Please unchecked if you have already index files
# - dir: directory where all indexed are written
# - name: name of prefix use in all mapping rules
# - fasta: path to Reference Genome in fasta format


#
genome:
  index: yes
  genome_directory: /path/to/your/directory
  name: "hg19" #path to index name
  fasta_file: /path/to/your/directory/Genomes/hg19/hg19.fa



#################################################################
# FastQC section
#
# :Parameters:
#
# - do: if unchecked, this rule is ignored
# - options: string with any valid FastQC options
#
fastqc:
    do: yes
    options: "--nogroup"


#######################################################################
# Quality trimming and adapter removal
#
# If a design_file is provided the forward and reverse complement adapters
# are automatically extracted from this file (given the sample name contained
# in the filenames). In such case, the fwd and rev fields are ignored.
#
# If there is no design_file, the fwd and rev fields are used. It can be a
# string, or a filename. If a filename, it must be prefixed with "file:" to
# specify that it is a file and not a string. If the tool is cutadapt, the empty
# fwd and rev fields means that no adapters are to be used.
#
# :Parameters:
#
# - adapter_type: can only be one of PCRFree, Nextera, Rubicon, TruSeq.
#   Only used if design_file is provided.
# - design_file: a valid CSV file with mapping of index and sample name
# - fwd: a string or file (prefixed with *file:*)
# - m: 20 means discard trimmed reads that are shorter than 20.
#         must be > 0
# - quality: 0 means no trimming, 30 means keep base with quality
#        above 30
# - mode: must be set to one of
#     - g for 5'
#     - a for 3'
#     - b for both 5'/3'
# - rev: a string or file (prefixed with *file:*)
# - tool: only cutadapt supported for now
# - threads: number of threads to use (atropos only)
# - options: See cutadapt documentation for details on
#            cutadapt.readthedocs.io. We change the default value
#            of -O to 6 (at least 6 bases are required to match before
#            trimming of an adapter)
#
# :Note: If design_file is provided, fwd and rev are ignored
#
#   ref: http://cutadapt.readthedocs.io/
# adapter_choice__ = ["", "PCRFree", "Rubicon", "Nextera", "TruSeq"]
# tool_choice__ = ["atropos", "cutadapt"]
cutadapt:
    do: yes
    tool_choice: cutadapt
    adapter_choice:
    design_file:
    fwd:
    rev:
    m: 25                       # {"strict_min": 0}
    mode: "b"                   # {"values": ["b","g","a"]}
    options: "-O 6 --trim-n --max-n 1"
    quality: 30                 # {"range": [0,40]}
    threads: 4


#############################################################################
# bowtie2_mapping used to align reads against genome file
#
# :Parameters:
#
# - do: if unchecked, this rule is ignored
# - options: any options recognised by bowtie2 tool
# - threads: number of threads to be used
#
bowtie2_mapping:
    do: yes
    #options: "--dovetail --no-mixed --no-discordant " for paired-end data
    options: ""
    threads: 4


#############################################################################
# mark duplicates (picard-tools) allows to mark PCR duplicate in BAM files
#
# :Parameters:
#
# - do: if unchecked, this rule is ignored. Mandatory for RNA-SeQC tool.
# - remove: If true do not write duplicates to the output file instead of writing them with
#            appropriate flags set.  Default value: true. Have to be True
# - tmpdir: write tempory file on this directory (default /tmp/, but could be "/local/scratch/")
#
mark_duplicates:
    do: yes
    remove: 'True' ## Have to be True
    tmpdir: "/tmp/"
    threads: 4


#############################################################################
# remove blacklist
#
# :Parameters:
#
# - do: if unchecked, this rule is ignored.
# - blacklist_file: path to BED file containing all blacklisted regions
#
remove_blacklist:
    do: yes
    blacklist_file: /path/to/your/directory/Genomes/hg19/hg19_blacklist.bed
    threads: 1



#############################################################################
# peak calling blabla
#
# :Parameters:
#
# - model: model used by MACS2. Could be 'narrow' or 'broad'.
# - no-model: use --no-model option. See MACS2 documentation. Possible values: {yes, no}
# - force_shift: Possible values: {yes, no}
# - options: any option recognized by MACS2. For paired-end reads, it is very recommended
# to put --keep-dup 2500
# - genomeSize: It's the mappable genome size or effective genome size which is defined as the genome size which can
# be sequenced. Because of the repetitive features on the chromsomes, the actual mappable genome size will be smaller
# than the original size, about 90% or 70% of the genome size. The default hs -- 2.7e9 is recommended for UCSC human
# hg18 assembly.
# - readLength: in order to compute the best shift with PPQT when force_shift is set
#
# tool_choice__ = ["narrow", "broad"]
#
peak_calling:
    model_choice: 'narrow'    ## may be broad
    no_model: no             ## may be yes
    force_shift: no           ## may be yes
    options: "--keep-dup 2500 "
    cutoff: "0.01"
    genomeSize: mm
    readLength: 50


#############################################################################
# Compute IDR on replicates, pseudo-replicates and pooled replicates
#
# :Parameters:
#
# - rank: Which column to use to rank peaks. Options: signal.value p.value q.value columnIndex
# - thresh: Report statistics for peaks with a global idr below this value but return all peaks with an idr below --idr. Default: 0.05
#
# mode_choice__ = ['narrowPeak', 'broadPeak', 'bed', 'gff']
#
compute_idr:
    rank: 'signal.value'
    thresh: 0.05

#############################################################################
# Compute differential analysis
#
# :Parameters:
#
# - method:
# - normalization:
# - spikes:
# - pAdjustMethod:
# - alpha:
# - batch:
#

statistical_analysis:
    do: no
    method: "Limma" #Limma
    normalisation: "scale" #"scale"
    spikes: NULL
    pAdjustMethod: "BH"
    alpha: 0.05
    batch: NULL


#############################################################################
# bamCoverage write file in bigwig format from BAM files.
# This tool takes an alignment of reads or fragments as input (BAM file) and
# generates a coverage track (bigWig or bedGraph) as output. The coverage is
# calculated as the number of reads per bin, where bins are short consecutive
# counting windows of a defined size. It is possible to extended the length of
# the reads to better reflect the actual fragment length. *bamCoverage* offers
# normalization by scaling factor, Reads Per Kilobase per Million mapped reads
# (RPKM), and 1x depth (reads per genome coverage, RPGC).
#
# :Parameters:
#
# - do: if unchecked, this rule is ignored
# - binSize: Size of the bins, in bases, for the output of the
#            bigwig/bedgraph file. (default: 50)
# - genomeSize: Report read coverage normalized to 1x sequencing depth
#                        (also known as Reads Per Genomic Content (RPGC)).
#                        Sequencing depth is defined as: (total number of
#                        mapped reads * fragment length) / effective genome
#                        size. The scaling factor used is the inverse of the
#                        sequencing depth computed for the sample to match the
#                        1x coverage. To use this option, the effective genome
#                        size has to be indicated after the option. The
#                        effective genome size is the portion of the genome
#                        that is mappable.
# - extendReads: This parameter allows the extension of reads to
#                fragment size.
# - minFragmentLength: The minimum fragment length needed for read/pair
#                      inclusion. Note that a value other than 0 will exclude
#                      all single-end reads.
# - maxFragmentLength: The maximum fragment length needed for read/pair
#                      inclusion. A value of 0 disables filtering and is
#                      needed for including single-end and orphan reads.
# - threads: number of threads to be used
# - chromSize: path to index of reference genome obtain by samtools faidx


coverage:
    do: no
    binSize: 10
    genomeSize : 2150570000 ##mm10
    extendReads: 65
    minFragmentLength: 0 #Note that a value other than 0 will exclude all single-end reads.
    maxFragmentLength: 0 #A value of 0 disables filtering and is needed for including single-end and orphan reads.
    threads: 4
    chromSize_file: hg19.chrom.sizes




#############################################################################
#   MultiQC aggregates results from bioinformatics analyses across many
#   samples into a single report.
#
# :Parameters:
#
# - options: any options recognised by multiqc
# - output-directory: Create report in the specified output directory
#
multiqc:
    options: "-c multiqc_config.yaml -f  -e macs2 -x 3-Deduplication/*spikes* -x 2-Mapping/*_spike*"
    output-directory: "11-Multiqc"
    config_file: "multiqc_config.yaml"